export const fonts = [
  { label: "Cinzel", family: "Cinzel, Trajan Pro, Times New Roman, serif" },
  { label: "Cormorant Garamond", family: "Cormorant Garamond, Garamond, serif" },
  { label: "Playfair Display", family: "Playfair Display, Georgia, serif" },
  { label: "Libre Baskerville", family: "Libre Baskerville, Baskerville, serif" },
  { label: "Great Vibes", family: "Great Vibes, Edwardian Script ITC, cursive" },
  { label: "Montserrat", family: "Montserrat, Arial, sans-serif" },
  { label: "Arial", family: "Arial, Helvetica, sans-serif" },
  { label: "Arial Black", family: "Arial Black, Impact, sans-serif" },
  { label: "Baskerville", family: "Baskerville, Libre Baskerville, serif" },
  { label: "Bodoni MT", family: "Bodoni MT, Didot, serif" },
  { label: "Book Antiqua", family: "Book Antiqua, Palatino, serif" },
  { label: "Calibri", family: "Calibri, Arial, sans-serif" },
  { label: "Cambria", family: "Cambria, Georgia, serif" },
  { label: "Century Gothic", family: "Century Gothic, Montserrat, sans-serif" },
  { label: "Copperplate Gothic", family: "Copperplate Gothic Light, Cinzel, serif" },
  { label: "Franklin Gothic", family: "Franklin Gothic Medium, Arial, sans-serif" },
  { label: "Garamond", family: "Garamond, Cormorant Garamond, serif" },
  { label: "Georgia", family: "Georgia, serif" },
  { label: "Gill Sans", family: "Gill Sans, Calibri, sans-serif" },
  { label: "Helvetica", family: "Helvetica, Arial, sans-serif" },
  { label: "Impact", family: "Impact, Arial Black, sans-serif" },
  { label: "Lucida Calligraphy", family: "Lucida Calligraphy, Great Vibes, cursive" },
  { label: "Palatino", family: "Palatino Linotype, Book Antiqua, serif" },
  { label: "Perpetua", family: "Perpetua, Georgia, serif" },
  { label: "Rockwell", family: "Rockwell, Georgia, serif" },
  { label: "Times New Roman", family: "Times New Roman, Times, serif" },
  { label: "Trajan Style", family: "Trajan Pro, Cinzel, serif" },
  { label: "Verdana", family: "Verdana, Geneva, sans-serif" }
];
